{% set name = "apache-airflow-providers-jenkins" %}
{% set version = "4.1.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_jenkins-{{ version }}.tar.gz
  sha256: 6b53b7e378fa41c93a1403559c525d635bd6702495c82129d44d94a77cd79f68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-compat >=1.8.0
    - python-jenkins >=1.8.2

test:
  imports:
    - airflow.providers.jenkins
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-jenkins for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/jenkins/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-jenkins/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
