{% set name = "apache-airflow-providers-jenkins" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_jenkins-{{ version }}.tar.gz
  sha256: 399296530de33fcad75cd4c1df396f8d88462ca2b304baf73aa508f5f81e94f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.11.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0
    - python-jenkins >=1.0.0

test:
  imports:
    - airflow.providers.jenkins
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-jenkins for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/jenkins/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-jenkins/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
